config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :lists
  resources :tables
  resources :list_members, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  root to: 'static#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :username,
            presence: true,
            length: { maximum: 20 },
            format: { with: /\A[\w_-]+\z/i }
  
  has_many :tables, dependent: :destroy
  has_many :lists, dependent: :destroy

  has_many :f_followers, class_name: 'Follow', foreign_key: "following_id", dependent: :destroy
  has_many :f_following, class_name: 'Follow', foreign_key: "follower_id", dependent: :destroy

  has_many :followers, through: 'f_followers', source: 'follower'
  has_many :following, through: 'f_following', source: 'following'

  has_one_attached :avatar
  
  def to_param
    username
  end

  def activity_feed
    PublicActivity::Activity.where(owner: following)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_account_update_params
  #  devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  #end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find_by(username: params[:id])
    if !@follow = Follow.where(following_id: @user.id, follower_id: current_user.id).first
      @follow = Follow.new
    end
    @tables = @user.tables.paginate(page: params[:page])
  end
end

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<header class="user">
  <% if @user.avatar.attached? %>

    <%= image_tag @user.avatar, class: "avatar" %>
    <% else %>
    <%= image_tag 'avatar.png', class: "avatar" %>
    <% end %>

  <span class="usernames">
    <h2><%= '@'+@user.username %></h2>
    <% if (defined? @user.name && @user.name.present?) %>
    <div class="name"><%= @user.name %></div>
    <% end %>
  </span>
</header>
<% if @user != current_user %>
  <% if @follow.following.present? %>
    <%= link_to 'Unfollow', @follow, :method => 'delete' %>
  <% else %>
    <%= form_with(model: @follow) do |f| %>
      <%= f.hidden_field :following_id, value: @user.id %>
      <%= f.submit "Follow" %>
    <% end %>
  <% end %>
<% end %>  

<% if (((defined? @user.web) && @user.web.present?) || ((defined? @user.itch) && @user.itch.present?) || ((defined? @user.twitter) && @user.twitter.present?)) %>
<ul id="userlinks">
  <% if (defined? @user.web) && @user.web.present? %>
  <li><strong>Website: </strong><%= link_to @user.web, url_with_protocol(@user.web), :target => '_blank' %></li>
  <% end %>
  <% if (defined? @user.itch) && @user.itch.present? %>
  <li><strong>Itch.io: </strong><%= link_to @user.itch + ' on Itch.', 'https://'+@user.itch+'.itch.io/', :target => '_blank' %></li>
  <% end %>
  <% if (defined? @user.twitter) && @user.twitter.present? %>
  <li><strong>Twitter: </strong><%= link_to '@'+@user.twitter, 'https://twitter.com/'+@user.twitter, :target => '_blank' %></li>
  <% end %>
</ul>
<% end %>

<div class="right">
  <% if current_user == @user %>
    <div class="supportLink"><%= link_to 'Edit profile', edit_registration_path(current_user) %></div>
  <% elsif (defined? @user.support) && @user.support.present? %>
    <div class="supportLink"<%= link_to 'Like this user’s work? Support them here.',
	url_with_protocol(@user.support), :target => '_blank' %></div>
  <% end %>

  <% if @user.lists.any? %>
  <div class="highlight">
    <h3>Lists</h3>
    <ul>
      <% @user.lists.each do |l| %>
      <li><%= link_to l.name, l %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>

<div class="left">
  <% if @tables.any? %>
  <%= will_paginate @tables %>
  <section id="tables">
    <%= render @tables %>
  </section>
  <%= will_paginate @tables %>
  <% else %>
  <p>This user hasn’t created any tables yet!</p>
  <% end %>
</div>