config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :lists
  resources :tables
  resources :list_members, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
  root to: 'static#index'
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_table, only: [:show, :edit, :update, :destroy]
  before_action :table_owner, only: [:edit, :update, :destroy]
  
  def index
    @tables = Table.all.where(:draft => false, :private =>false).order("created_at DESC")
    if (defined? search_params[:terms])
      @searchterms = search_params[:terms]
      @tables = @tables.search(search_params[:terms])
    end
    
    @tables = @tables.paginate(page: params[:page])
  end

  def show
    unless (@table.private || @table.draft) && @table.user != current_user
      @listmember = ListMember.new
    else
      render status: :forbidden
    end
  end

  def new
    @dice = Die.all
    @table = Table.new
    4.times do
      r = Row.new
      @table.rows << r
    end
    @table
  end

  def create
    table = current_user.tables.build(table_params)

    if table.save!
      table.create_activity :create, owner: current_user
      redirect_to table
    else
      redirect_to new_table_path
    end
  end

  def edit
    @dice = Die.all
  end

  def update
    if @table.update(table_params)
      @table.create_activity :update, owner: current_user
      flash[:success] = "Table updated!"
      redirect_to @table
    else
      render 'edit'
    end
  end

  def destroy
    @table.destroy
    flash[:success] = "Table deleted"
    redirect_to tables_path
  end
  
  private
  def search_params
    params.require(:search).permit(:terms)
  end
  
  def table_params
    params.require(:table).permit(:title, :description, :die_id, :draft, :private,
                                  rows_attributes: [:id, :num, :name, :description, :_destroy])
  end

  def set_table
    @table = Table.find(params[:id])
  end

  def table_owner
    redirect_to root_path unless current_user = @table.user
  end
end

app/helpers/table_helper.rb
module TableHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: @table, id: 'tableForm') do |f| %>

<%= render 'shared/error_messages', object: f.object %>

<script>
window.onload = function() {
	let dice = JSON.parse('<%= raw(Die.all.to_json) %>');
	let lastValue = dice[document.getElementById('table_die_id').value - 1];

	document.getElementById('table_die_id').addEventListener('change', function(e) {
		let die = dice[e.target.value - 1];
		let table = document.getElementById('formTable');
		let currentRows = table.rows.length - 1;

		// Shrinking table
		if (lastValue.numbers.length > die.numbers.length) {
			if (confirm("This will shrink the current table and rows above " + lastValue.numbers.length + " will be lost. Continue?")) {
				Array.prototype.forEach.call(table.rows, function(value, index, array) {
					table.rows[index].cells[0].firstChild.value = die.numbers[index-1];
					if ((index-1) >= die.numbers.length) {
						table.rows[index].style.display = 'none';
						table.rows[index].cells[2].innerHTML += `<input type="hidden" value="true" name="table[rows_attributes][${index-1}[_destroy]" id="table_rows_attributes_${index-1}_destroy">`;
					}
				});
				lastValue = dice[e.target.value - 1];
			} else {
				// Cancelled. Reset die select.
				e.target.value = lastValue.name;
			}
			// Growing table
		} else {
			die.numbers.forEach(function(value, index, array) {
			if ((index) >= lastValue.numbers.length) {
				if (typeof table.rows[index+1] !== 'undefined') {
					// Row exists but hidden
					table.rows[index+1].style.display = "";
					console.log(index);
					let deleteNode = document.getElementById(`table_rows_attributes_${index}_destroy`);
					deleteNode.parentNode.removeChild(deleteNode);
				} else {
					let row = table.insertRow(-1);
					row.innerHTML = `<td><input class="rowNo no-spinners" type="number" value="${index+1}" name="table[rows_attributes][${index+1}][num]" id="table_rows_attributes_${index+1}_num"></td>
								<td><input type="text" value="" name="table[rows_attributes][${index+1}][name]" id="table_rows_attributes_${index+1}_name"></td>
								<td><input type="text" value="" name="table[rows_attributes][${index+1}][description]" id="table_rows_attributes_${index+1}_description">`;
				}
			} else {
				console.log('mm');
			}
			// Renumber
			table.rows[index+1].cells[0].firstChild.value = die.numbers[index];
			});

			lastValue = dice[e.target.value - 1];
		}
	});
}
</script>

<%= f.collection_select :die_id, Die.all, :id, :name %>
<%= f.text_field :title, placeholder: "Table title", class: "titleField" %>
<%= f.text_area :description, placeholder: "Table description", class: "descriptionInput" %>

<table id="formTable">
  <thead>
  <tr>
    <th class="numCol">No.</th>
    <th class="nameCol">Name</th>
    <th class="descriptionCol">Description</th>
  </tr>
  </thead>
  <tbody>
    <%= f.fields_for :rows, @table.rows.order('num') do |row_f| %>
    <tr>
      <td><%= row_f.number_field :num, class: 'no-spinners rowNo' %></td>
      <td><%= row_f.text_field :name %></td>
      <td><%= row_f.text_field :description %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="tableOptions">
  <% if defined? delete %>
  <%= link_to 'Delete table', @table, method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
  <%= f.label :draft, class: 'formoptions' %>
  <%= f.check_box :draft, class: 'formoptions' %>
  <%= f.label :private, class: 'formoptions' %>
  <%= f.check_box :private, class: 'formoptions' %>
</div>
<%= f.submit yield(:button_text) %>

<% end %>

app/views/tables/_row_fields.html.erb
<tr class="tableRow">
  <td><%= form.number_field :num, class: 'rowNo no-spinners' %></td>
  <td><%= form.text_field :name %></td>
  <td><%= form.text_field :description %></td>
</tr>

app/views/tables/_search.html.erb
<%= form_with(url: tables_path, method: :get, class: "search") do |f| %>
<h2>Find a table</h2>
<%= text_field :search, :terms, placeholder: "Enter search terms" %>
<%= f.submit 'Search' %>
<% end %>

app/views/tables/_table.html.erb
<div class="table">
<h3><%= link_to table.title, table, class: 'nodec' %>
  <span class="name">by
    <%= link_to table.user do %>
    <% if table.user.avatar.attached? %>
    <%= image_tag table.user.avatar.variant(resize: "40 x 40"), class: "avatar" %>
    <% else %>
    <%= image_tag 'avatar.png', width: "40px", height: "40px", class: "avatar" %>    
    <% end %>
    <%= table.user.username %>
    <% end %>
</span></h3>

<% if (defined? lm) %>
<%= link_to "Remove from list", lm, method: :delete,
    data: { confirm: 'Are you sure you want to remove this table from the list?' },
    class: 'remove_link' %>
<% end %>

<% if (defined? table.descriptiom) && !table.description.empty? %>
<div class="tableDescription"><%= table.description %></div>
<% end %>

<%= link_to table, class: 'nodec' do %>
<table id="table-<%= table.id %>" class="fade">
  <tr>
    <th>No.</th>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% table.rows.order('num').take(4).each do |r| %>
  <tr>
    <td><%= r.num %></td>
    <td><%= r.name %></td>
    <td><%= r.description %></td>
  </tr>
  <% end %>
</table>
<% end %>
</div>

app/views/tables/edit.html.erb
<% provide(:title, 'Edit ' + @table.title) %>
<% provide(:button_text, 'Save edits') %>

<%= render 'form', delete: true %>

app/views/tables/index.html.erb
<% provide(:title, "All tables") %>

<% if @tables.any? %>
<%= will_paginate %>
<section id="tables">
  <%= render @tables %>
</section>
<%= will_paginate @tables %>
<% end %>

app/views/tables/new.html.erb
<% provide(:title, 'New table') %>
<% provide(:button_text, 'Create') %>

<%= render 'form' %>

app/views/tables/show.html.erb
<% provide(:title, @table.title) %>

<% if @table.draft %>
<p class="notice">This table is currently a draft.</p>
<% end %>
<% if @table.private %>
<p class="notice">This table is private</p>
<% end %>

<h2><%= @table.die.name %> <%= @table.title %></h2>
<% if (defined? @table.description) && @table.description.present? %>
<div class="tableDescription"><%= @table.description %></div>
<% end %>

<div class= "highlight right">
<% if @table.user == current_user %>
<%= link_to 'Edit table', edit_table_path(@table), class: "editLink" %>
<% end %>

<%= link_to 'Share on Twitter',
    'https://twitter.com/intent/tweet?url='+table_url(@table)+
    '&text=Check+out+this+great+table+on+Tabled+by+'+@table.user.username+'!'+
    '&hashtags=ttrpg,tabled', class: 'editLink' %>

<% if user_signed_in? %>
  <%= form_with(model: @listmember, class: 'listmember') do |f| %>
    <%= f.hidden_field :table_id, value: @table.id %>
    <%= f.select :list_id, current_user.lists.collect { |l| [ l.name, l.id ] }, { include_blank: 'New list' } %>
    <%= f.submit "Add table to list" %>
  <% end %>
<% end %>
</div>
<div class="left">
<table id="table-<%= @table.id %>">
  <tr>
    <th class="num">No.</th>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @table.rows.order('num').each do |r| %>
  <tr>
    <td><%= r.num %></td>
    <td><%= r.name %></td>
    <td><%= r.description %></td>
  </tr>
  <% end %>
</table>

</div>